# General
name: Konrad
description: "Cardiac MRI"
url: http://mrkonrad.github.io/MRKonrad
# url: http://localhost:4000

#markdown: redcarpet
markdown: kramdown
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: kwerys
bitbucket: kwerys
twitter: MR_Konrad
github: MRKonrad
google: 110666846551233806516 
researchgate: Konrad_Werys

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"