# General
name: Konrad
description: "Cardiac MRI"
url: https://mrkonrad.github.io/MRKonrad
# url: http://localhost:4000

gems: [jekyll-paginate, jekyll-gist]

markdown: kramdown

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: kwerys
bitbucket: kwerys
twitter: MR_Konrad
github: MRKonrad
google: 110666846551233806516
researchgate: Konrad_Werys

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
